version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mawr
      POSTGRES_PASSWORD: metallica
      POSTGRES_DB: nlstore
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mawr -d nlstore"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: metallica
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "6432:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
